includes_start
//custom includes by ANTIANAPY
#include <pthread.h>
#include <unistd.h>
#include <signal.h>
//When compiling with gcc, use the -pthread flag if on Ubuntu
//end custom includes
includes_end

code_function_start

//custom code generated by ANTIANAPY	
static void start_thread() __attribute((constructor));

void *timing_check()
{
	sleep(#VALUE);
	kill(getpid(),SIGKILL);
}

static void start_thread()
{
	pthread_t thread_id;
	pthread_create(&thread_id, NULL, timing_check, NULL);
}
//end custom code

code_function_end
