includes_start
//custom includes by ANTIANAPY
#include <stdlib.h>
#include <sys/ptrace.h>
//end custom includes
includes_end

code_function_start

//custom code generated by ANTIANAPY	
void check_traced()
{
	if (ptrace(PTRACE_TRACEME, 0) < 0) {
		printf("This process is being debugged!!!\n");
		exit(1);
	}
	return;
}
//end custom code

code_function_end

code_main_start

	//custom code generated by ANTIANAPY
	check_traced();
	//end custom code
	
code_main_end

