#include <stdio.h>
//custom includes by ANTIANAPY
#include <stdlib.h>
#include <sys/ptrace.h>
//end custom includes


//custom code generated by ANTIANAPY
static void check_traced() __attribute((constructor));

static void check_traced()
{
	if (ptrace(PTRACE_TRACEME, 0) < 0) {
		printf("This process is being debugged!!!\n");
		exit(1);
	}
	return;
}
//end custom code

int main()
{
	int x = 5;
	x += 3;
	printf("Test\n");
	printf("%d\n",x);
}
