#include <stdio.h>
#include <unistd.h>
//custom includes by ANTIANAPY
#include <pthread.h>
#include <signal.h>
//When compiling with gcc, use the -pthread flag if on Ubuntu
//end custom includes


//custom code generated by ANTIANAPY	
void *timing_check()
{
	sleep(3);
	kill(getpid(),SIGKILL);
}
//end custom code

int main()
{

	//custom code generated by ANTIANAPY	
	pthread_t thread_id;
	pthread_create(&thread_id, NULL, timing_check, NULL);
	//end custom code
	
	int x = 5;
	x += 3;
	printf("Test\n");
	sleep(2);
	printf("%d\n",x);
}
