#include <stdio.h>
//custom includes by ANTIANAPY
#include <stdlib.h>
#include <sys/ptrace.h>
//end custom includes

int main()
{

	//custom code generated by ANTIANAPY
	if (ptrace(PTRACE_TRACEME, 0) < 0) {
		printf("This process is being debugged!!!\n");
		exit(1);
	}
	//end custom code
	
	int x = 5;
	x += 3;
	printf("Test\n");
	printf("%d\n",x);
}
