#include <stdio.h>
//custom includes by ANTIANAPY
#include <pthread.h>
#include <unistd.h>
#include <signal.h>
//end custom includes

int main()
{

	//custom code generated by ANTIANAPY	
	pthread_t thread_id;
	pthread_create(&thread_id, NULL, timing_check, NULL);
	//end custom code
	
	int x = 5;
	x += 3;
	printf("Test\n");
	printf("%d\n",x);
}
