includes_start
//custom includes by ANTIANAPY
#include <stdlib.h>
#include <sys/ptrace.h>
//end custom includes
includes_end

code_main_start

	//custom code generated by ANTIANAPY
	if (ptrace(PTRACE_TRACEME, 0) < 0) {
		printf("This process is being debugged!!!\n");
		exit(1);
	}
	//end custom code
	
code_main_end
